apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: choremaster-app
  labels:
    app: {{ .Chart.Name }}
    component: app
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - choremaster.example.com
      secretName: choremaster-app-tls
  rules:
    - host: choremaster.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: choremaster-app
                port:
                  number: 80
